import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, Check, ChevronDown, ChevronLeft, ChevronRight, Instagram, Menu, Minus, Package, Phone, Plus, Search, ShieldCheck, ShoppingBag, Sparkles, X } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { getOffers, getProducts, submitOrder, supabase, type Offer, type Product } from '@/lib/supabase';
import { toast } from 'sonner';

const videoUrl = '/manus-storage/foamx_ad_landscape_a61cc867.mp4';
const showcaseVideoUrl = '/manus-storage/a7a81051-78eb-4ebb-98c3-e4619cb77002_e2642fec.mp4';
const productVideoUrls: Record<string, string> = {
  'ceramic-wash': '/media/ceramic-wash.mp4',
  'foam-shampoo': '/media/foam-shampoo.mp4',
};
const logoUrl = '/media/foamx-logo.png';
type CartItem = Product & { quantity: number };

function money(value: number) { return `₹${value.toLocaleString('en-IN')}`; }

export default function Home() {
  const [products, setProducts] = useState<Product[]>([]);
  const [offers, setOffers] = useState<Offer[]>([]);
  const [cart, setCart] = useState<CartItem[]>([]);
  const [activeProduct, setActiveProduct] = useState<Product | null>(null);
  const [cartOpen, setCartOpen] = useState(false);
  const [checkoutOpen, setCheckoutOpen] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  const [submittedOrder, setSubmittedOrder] = useState<string | null>(null);
  const [adminOpen, setAdminOpen] = useState(false);
  const [adminEmail, setAdminEmail] = useState('');
  const [adminOrders, setAdminOrders] = useState<any[]>([]);
  const [isAdmin, setIsAdmin] = useState(false);
  const [loading, setLoading] = useState(true);

  useEffect(() => { Promise.all([getProducts(), getOffers()]).then(([p, o]) => { setProducts(p); setOffers(o); }).finally(() => setLoading(false)); }, []);
  useEffect(() => { const client = supabase; if (!client) return; const checkAdmin = async () => { const { data: session } = await client.auth.getSession(); if (!session.session) return; const { data: profile } = await client.from('profiles').select('role').eq('id', session.session.user.id).single(); if (profile?.role === 'admin') { setIsAdmin(true); const { data } = await client.from('orders').select('*').order('created_at', { ascending: false }); setAdminOrders(data ?? []); } }; checkAdmin(); const { data } = client.auth.onAuthStateChange(() => { checkAdmin(); }); return () => data.subscription.unsubscribe(); }, []);
  const total = useMemo(() => cart.reduce((sum, item) => sum + item.price * item.quantity, 0), [cart]);
  const count = cart.reduce((sum, item) => sum + item.quantity, 0);
  const addToCart = (product: Product) => { setCart(items => { const found = items.find(i => i.id === product.id); return found ? items.map(i => i.id === product.id ? { ...i, quantity: i.quantity + 1 } : i) : [...items, { ...product, quantity: 1 }]; }); toast.success(`${product.name} added to your garage kit`); };
  const changeQuantity = (id: string, delta: number) => setCart(items => items.map(i => i.id === id ? { ...i, quantity: Math.max(0, i.quantity + delta) } : i).filter(i => i.quantity > 0));
  const scrollTo = (id: string) => { setMenuOpen(false); document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' }); };

  const placeOrder = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const form = new FormData(event.currentTarget);
    try {
      const result = await submitOrder({ customer_name: String(form.get('name')), phone: String(form.get('phone')), address: String(form.get('address')), items: cart.map(i => ({ product_id: i.id, product_name: i.name, price: i.price, quantity: i.quantity })), total });
      setSubmittedOrder(result.orderNumber); setCart([]); setCheckoutOpen(false); setCartOpen(false); toast.success('Booking request received');
    } catch { toast.error('Could not submit your booking. Please try again.'); }
  };

  const openAdmin = async () => {
    setAdminOpen(true);
    if (supabase) { const { data: session } = await supabase.auth.getSession(); if (!session.session) return; const { data: profile } = await supabase.from('profiles').select('role').eq('id', session.session.user.id).single(); if (profile?.role !== 'admin') { toast.error('This account is not authorized for team access.'); return; } const { data } = await supabase.from('orders').select('*').order('created_at', { ascending: false }); setAdminOrders(data ?? []); }
  };
  const updateStatus = async (id: string, status: string) => { if (!supabase) return; await supabase.from('orders').update({ status }).eq('id', id); setAdminOrders(o => o.map(x => x.id === id ? { ...x, status } : x)); };

  return <div className="min-h-screen bg-[#08090a] text-[#f5f3ef] selection:bg-[#d4a94d] selection:text-black">
    <header className="fixed top-0 z-40 w-full border-b border-white/10 bg-[#08090a]/75 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:px-8">
      <button onClick={() => scrollTo('top')} className="flex items-center gap-3"><img src={logoUrl} className="h-10 w-10 rounded-full object-cover" alt="FOAMX logo" /><span className="text-lg font-black tracking-[.28em]">FOAMX</span></button>
      <nav className="hidden items-center gap-8 text-[11px] font-semibold uppercase tracking-[.2em] text-white/65 md:flex"><button onClick={() => scrollTo('products')} className="hover:text-[#d4a94d]">Products</button><button onClick={() => scrollTo('offers')} className="hover:text-[#d4a94d]">Offers</button><button onClick={() => scrollTo('story')} className="hover:text-[#d4a94d]">About</button><button onClick={() => scrollTo('contact')} className="hover:text-[#d4a94d]">Contact</button></nav>
      <div className="flex items-center gap-3"><button onClick={() => setCartOpen(true)} className="relative rounded-full border border-white/15 p-3 hover:border-[#d4a94d]"><ShoppingBag size={17}/>{count > 0 && <span className="absolute -right-1 -top-1 grid h-5 w-5 place-items-center rounded-full bg-[#d4a94d] text-[10px] font-bold text-black">{count}</span>}</button><button onClick={() => setMenuOpen(v => !v)} className="rounded-full border border-white/15 p-3 md:hidden"><Menu size={17}/></button></div>
    </div>{menuOpen && <div className="border-t border-white/10 bg-[#0d0f10] p-5 md:hidden"><div className="grid gap-4 text-xs font-bold uppercase tracking-[.2em] text-white/70"><button onClick={() => scrollTo('products')}>Products</button><button onClick={() => scrollTo('offers')}>Offers</button><button onClick={() => scrollTo('story')}>About</button><button onClick={() => scrollTo('contact')}>Contact</button></div></div>}</header>

    <main id="top"><section className="relative flex min-h-[760px] items-end overflow-hidden border-b border-white/10 pt-20"><video autoPlay muted loop playsInline preload="auto" onLoadedMetadata={event => { event.currentTarget.muted = true; void event.currentTarget.play().catch(() => undefined); }} className="absolute inset-0 h-full w-full object-cover brightness-125 opacity-70" src={videoUrl}/><div className="absolute inset-0 bg-[linear-gradient(90deg,#08090a_5%,transparent_60%,#08090a_100%)]"/><div className="absolute inset-0 bg-[linear-gradient(0deg,#08090a_0%,transparent_55%,rgba(8,9,10,.45)_100%)]"/><div className="relative mx-auto w-full max-w-7xl px-5 pb-24 lg:px-8"><motion.div initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .7 }} className="max-w-2xl"><p className="mb-7 flex items-center gap-3 text-xs font-bold uppercase tracking-[.32em] text-[#d4a94d]"><span className="h-px w-10 bg-[#d4a94d]"/>Automotive care, elevated</p><h1 className="font-display text-6xl font-black uppercase leading-[.88] tracking-[-.055em] sm:text-8xl lg:text-[9.5rem]">Clean<br/><span className="text-[#d4a94d]">without</span><br/>compromise.</h1><p className="mt-8 max-w-md text-sm leading-7 text-white/60">Professional-grade detailing chemistry for the people who refuse to settle for ordinary shine.</p><div className="mt-9 flex flex-wrap gap-3"><Button onClick={() => scrollTo('products')} className="rounded-none bg-[#d4a94d] px-7 py-6 text-xs font-black uppercase tracking-[.18em] text-black hover:bg-[#edd078]">Shop the collection <ArrowRight size={15} className="ml-3"/></Button><button onClick={() => scrollTo('story')} className="flex items-center gap-2 border border-white/20 px-7 py-3 text-xs font-bold uppercase tracking-[.18em] hover:border-[#d4a94d]">Explore FOAMX <ChevronDown size={15}/></button></div></motion.div></div><div className="absolute bottom-9 right-8 hidden text-right text-[10px] uppercase tracking-[.25em] text-white/35 lg:block">Drag. Wash. Reveal.<br/><span className="text-[#d4a94d]">Designed in India</span></div></section>

    <section className="relative overflow-hidden border-b border-white/10 bg-black"><div className="relative h-[520px] sm:h-[680px] lg:h-[780px]"><video autoPlay muted loop playsInline preload="auto" onLoadedMetadata={event => { event.currentTarget.muted = true; void event.currentTarget.play().catch(() => undefined); }} className="absolute inset-0 h-full w-full object-cover brightness-125" src={showcaseVideoUrl}/><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(8,9,10,.9),rgba(8,9,10,.18)_65%,rgba(8,9,10,.65))]"/><div className="absolute inset-0 bg-[linear-gradient(0deg,rgba(8,9,10,.9),transparent_45%,rgba(8,9,10,.2))]"/><div className="relative mx-auto flex h-full max-w-7xl items-end px-5 pb-12 lg:px-8 lg:pb-20"><div className="max-w-xl"><p className="eyebrow">The FOAMX ritual</p><h2 className="mt-4 font-display text-5xl font-black uppercase leading-[.9] tracking-[-.04em] sm:text-7xl">Make every<br/><span className="text-[#d4a94d]">wash count.</span></h2><p className="mt-5 max-w-md text-sm leading-7 text-white/60">A closer look at the formulas, the finish, and the obsession behind a sharper clean.</p></div><span className="absolute right-8 top-8 hidden text-[10px] font-bold uppercase tracking-[.24em] text-white/45 md:block">FOAMX / Showcase 02</span></div></div></section>\n\n    <section id="story" className="mx-auto grid max-w-7xl gap-12 px-5 py-24 lg:grid-cols-[.8fr_1.2fr] lg:px-8 lg:py-32"><div><p className="eyebrow">The FOAMX standard</p><h2 className="mt-5 font-display text-5xl font-black uppercase leading-none tracking-[-.04em] sm:text-7xl">Your car.<br/><span className="text-[#d4a94d]">Our obsession.</span></h2></div><div className="grid gap-10 sm:grid-cols-2"><div className="border-l border-[#d4a94d] pl-6"><ShieldCheck className="mb-5 text-[#d4a94d]"/><h3 className="mb-3 font-display text-2xl font-bold uppercase">Detailer grade</h3><p className="text-sm leading-7 text-white/50">Purpose-built formulas that turn the most routine wash into a considered ritual.</p></div><div className="border-l border-white/20 pl-6"><Sparkles className="mb-5 text-[#d4a94d]"/><h3 className="mb-3 font-display text-2xl font-bold uppercase">Finish first</h3><p className="text-sm leading-7 text-white/50">Every product is tuned for gloss, slickness, and that just-detailed feeling.</p></div></div></section>

    <section id="products" className="border-y border-white/10 bg-[#0c0e0f] px-5 py-24 lg:px-8 lg:py-32"><div className="mx-auto max-w-7xl"><div className="mb-12 flex items-end justify-between"><div><p className="eyebrow">The collection / 01</p><h2 className="mt-4 font-display text-5xl font-black uppercase tracking-[-.04em] sm:text-7xl">Wash <span className="text-white/25">system</span></h2></div><span className="hidden text-xs uppercase tracking-[.2em] text-white/35 sm:block">{products.length || 2} essentials</span></div>{loading ? <div className="grid gap-5 md:grid-cols-2"><div className="h-96 animate-pulse bg-white/5"/><div className="h-96 animate-pulse bg-white/5"/></div> : <div className="grid gap-5 md:grid-cols-2">{products.map((product, index) => <motion.article key={product.id} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * .1 }} className="group border border-white/10 bg-[#111314] p-4"><div className="relative aspect-[1.25] overflow-hidden bg-[#e9e9e7]">{productVideoUrls[product.slug] ? <video autoPlay muted loop playsInline preload="auto" onLoadedMetadata={event => { event.currentTarget.muted = true; void event.currentTarget.play().catch(() => undefined); }} className="h-full w-full object-cover brightness-110 transition duration-700 group-hover:scale-105" src={productVideoUrls[product.slug]}/> : <img src={product.image_url} alt={product.name} className="h-full w-full object-contain p-8 mix-blend-multiply transition duration-700 group-hover:scale-105"/>}<div className="absolute inset-0 bg-gradient-to-t from-black/25 via-transparent to-transparent"/><Badge className="absolute left-4 top-4 rounded-none bg-black px-3 py-1 text-[9px] uppercase tracking-[.2em] text-white">{index === 0 ? 'Best seller' : 'Core formula'}</Badge><button onClick={() => setActiveProduct(product)} className="absolute bottom-4 right-4 rounded-full bg-black/80 p-3 opacity-0 backdrop-blur transition group-hover:opacity-100"><Search size={16}/></button></div><div className="flex items-start justify-between gap-5 px-2 pb-2 pt-6"><div><h3 className="font-display text-2xl font-bold uppercase">{product.name}</h3><p className="mt-2 max-w-sm text-xs leading-6 text-white/45">{product.description}</p></div><span className="font-display text-xl font-bold text-[#d4a94d]">{money(product.price)}</span></div><div className="mt-5 flex gap-2 px-2"><Button onClick={() => addToCart(product)} className="flex-1 rounded-none bg-[#d4a94d] text-xs font-black uppercase tracking-[.15em] text-black hover:bg-[#edd078]">Add to cart</Button><button onClick={() => setActiveProduct(product)} className="border border-white/15 px-5 text-xs font-bold uppercase tracking-[.15em] hover:border-[#d4a94d]">Details</button></div></motion.article>)}</div>}</div></section>

    <section id="offers" className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="border border-[#d4a94d]/35 bg-[#11100c] p-8 sm:p-12">{offers.length ? offers.map(o => <div key={o.id}><p className="eyebrow">Limited offer</p><h2 className="mt-4 font-display text-4xl font-black uppercase sm:text-6xl">{o.title}</h2><p className="mt-4 max-w-xl text-sm leading-7 text-white/55">{o.description}</p></div>) : <div className="flex flex-col justify-between gap-8 md:flex-row md:items-center"><div><p className="eyebrow">Offers / coming soon</p><h2 className="mt-4 font-display text-4xl font-black uppercase sm:text-6xl">No active <span className="text-[#d4a94d]">offers.</span></h2><p className="mt-4 max-w-lg text-sm leading-7 text-white/50">Check back soon for exclusive FOAMX deals. We are always working on a sharper way to keep your car looking its best.</p></div><div className="grid h-28 w-28 place-items-center rounded-full border border-[#d4a94d]/50 text-center text-[10px] font-bold uppercase tracking-[.18em] text-[#d4a94d]">Stay<br/>sharp</div></div>}</div></section>

    <section id="contact" className="border-t border-white/10 px-5 py-20 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-12 md:flex-row md:items-end"><div><p className="eyebrow">Start a conversation</p><h2 className="mt-4 font-display text-5xl font-black uppercase tracking-[-.04em] sm:text-7xl">Keep it<br/><span className="text-[#d4a94d]">flawless.</span></h2></div><div className="space-y-4 text-sm text-white/60"><a className="flex items-center gap-3 hover:text-[#d4a94d]" href="tel:+917306707640"><Phone size={17} className="text-[#d4a94d]"/>+91 73067 07640</a><a className="flex items-center gap-3 hover:text-[#d4a94d]" href="https://instagram.com/_foamx_" target="_blank" rel="noreferrer"><Instagram size={17} className="text-[#d4a94d]"/>instagram.com/_foamx_</a></div></div></section></main>
    <footer className="border-t border-white/10 px-5 py-8 lg:px-8"><div className="mx-auto flex max-w-7xl items-center justify-between text-[10px] uppercase tracking-[.2em] text-white/35"><span>© {new Date().getFullYear()} FOAMX</span><button onClick={openAdmin} className="hover:text-[#d4a94d]">Team access</button></div></footer>

    <AnimatePresence>{cartOpen && <div className="fixed inset-0 z-50"><div onClick={() => setCartOpen(false)} className="absolute inset-0 bg-black/70"/><motion.aside initial={{ x: '100%' }} animate={{ x: 0 }} exit={{ x: '100%' }} className="absolute right-0 h-full w-full max-w-md overflow-y-auto bg-[#111314] p-6"><div className="flex items-center justify-between border-b border-white/10 pb-5"><h2 className="font-display text-2xl font-bold uppercase">Your garage kit</h2><button onClick={() => setCartOpen(false)}><X/></button></div>{cart.length ? <><div className="divide-y divide-white/10">{cart.map(item => <div key={item.id} className="flex gap-4 py-5"><img src={item.image_url} className="h-20 w-20 bg-white object-contain p-2"/><div className="flex-1"><div className="flex justify-between"><h3 className="font-bold uppercase">{item.name}</h3><span className="text-[#d4a94d]">{money(item.price * item.quantity)}</span></div><div className="mt-4 flex items-center gap-3"><button onClick={() => changeQuantity(item.id, -1)} className="rounded-full border border-white/15 p-1"><Minus size={12}/></button><span>{item.quantity}</span><button onClick={() => changeQuantity(item.id, 1)} className="rounded-full border border-white/15 p-1"><Plus size={12}/></button></div></div></div>)}</div><div className="mt-8 border-t border-white/10 pt-6"><div className="flex justify-between text-lg font-bold"><span>Subtotal</span><span className="text-[#d4a94d]">{money(total)}</span></div><p className="mt-3 text-xs leading-5 text-white/40">No payment is required now. Submit a booking request and our team will contact you.</p><Button onClick={() => setCheckoutOpen(true)} className="mt-6 w-full rounded-none bg-[#d4a94d] py-6 text-xs font-black uppercase tracking-[.15em] text-black">Book this order <ArrowRight size={15} className="ml-2"/></Button></div></> : <div className="grid min-h-[60vh] place-items-center text-center"><div><ShoppingBag className="mx-auto mb-4 text-[#d4a94d]" size={30}/><p className="font-display text-2xl font-bold uppercase">Your kit is empty</p><p className="mt-2 text-sm text-white/40">Add a formula to get started.</p></div></div>}</motion.aside></div>}</AnimatePresence>
    <AnimatePresence>{activeProduct && <div className="fixed inset-0 z-50 grid place-items-center p-5"><div onClick={() => setActiveProduct(null)} className="absolute inset-0 bg-black/80"/><motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="relative max-h-[90vh] w-full max-w-3xl overflow-y-auto border border-white/15 bg-[#111314] p-5 sm:p-8"><button onClick={() => setActiveProduct(null)} className="absolute right-5 top-5 z-10"><X/></button><div className="grid gap-8 md:grid-cols-2"><div className="bg-[#e9e9e7] p-8"><img src={activeProduct.image_url} className="h-full max-h-80 w-full object-contain mix-blend-multiply"/></div><div className="flex flex-col justify-center"><p className="eyebrow">FOAMX formula</p><h2 className="mt-4 font-display text-4xl font-black uppercase">{activeProduct.name}</h2><p className="mt-4 text-sm leading-7 text-white/55">{activeProduct.description} Built for enthusiasts, tested in the real world, and made to leave a finish you can feel.</p><div className="mt-8 flex items-center justify-between border-y border-white/10 py-5"><span className="text-xs uppercase tracking-[.2em] text-white/45">Price</span><span className="font-display text-3xl font-bold text-[#d4a94d]">{money(activeProduct.price)}</span></div><Button onClick={() => { addToCart(activeProduct); setActiveProduct(null); setCartOpen(true); }} className="mt-6 rounded-none bg-[#d4a94d] py-6 text-xs font-black uppercase tracking-[.15em] text-black">Add to cart</Button></div></div></motion.div></div>}</AnimatePresence>
    <AnimatePresence>{checkoutOpen && <div className="fixed inset-0 z-[60] grid place-items-center overflow-y-auto p-5"><div onClick={() => setCheckoutOpen(false)} className="absolute inset-0 bg-black/80"/><motion.form onSubmit={placeOrder} initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="relative w-full max-w-lg border border-white/15 bg-[#111314] p-6 sm:p-8"><button type="button" onClick={() => setCheckoutOpen(false)} className="absolute right-5 top-5"><X/></button><p className="eyebrow">Booking request</p><h2 className="mt-4 font-display text-4xl font-black uppercase">Make it yours.</h2><p className="mt-3 text-xs leading-5 text-white/45">Payment is handled separately after our team confirms your order.</p><div className="mt-7 grid gap-4"><input required name="name" placeholder="Full name" className="field"/><input required name="phone" placeholder="Mobile number" className="field"/><textarea required name="address" placeholder="Full delivery address" rows={4} className="field resize-none"/></div><div className="mt-6 flex items-center justify-between border-t border-white/10 pt-5"><span className="text-sm text-white/45">Order total</span><b className="text-xl text-[#d4a94d]">{money(total)}</b></div><Button type="submit" className="mt-6 w-full rounded-none bg-[#d4a94d] py-6 text-xs font-black uppercase tracking-[.15em] text-black">Place booking request</Button></motion.form></div>}</AnimatePresence>
    {submittedOrder && <div className="fixed inset-0 z-[70] grid place-items-center p-5"><div className="absolute inset-0 bg-black/85"/><div className="relative w-full max-w-md border border-[#d4a94d]/40 bg-[#111314] p-8 text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-[#d4a94d] text-black"><Check/></div><p className="eyebrow mt-6">Booking confirmed</p><h2 className="mt-4 font-display text-4xl font-black uppercase">You’re on the list.</h2><p className="mt-4 text-sm leading-6 text-white/50">Your order ID is <strong className="text-white">{submittedOrder}</strong>. The FOAMX team will contact you for confirmation and delivery details.</p><Button onClick={() => setSubmittedOrder(null)} className="mt-7 rounded-none bg-white px-8 py-5 text-xs font-black uppercase tracking-[.15em] text-black">Continue browsing</Button></div></div>}
    {adminOpen && <div className="fixed inset-0 z-[80] overflow-y-auto bg-[#08090a] p-5 sm:p-10"><div className="mx-auto max-w-6xl"><div className="flex items-start justify-between"><div><p className="eyebrow">Restricted access</p><h2 className="mt-3 font-display text-5xl font-black uppercase">Order <span className="text-[#d4a94d]">control.</span></h2></div><button onClick={() => setAdminOpen(false)}><X/></button></div>{!isAdmin ? <div className="mt-16 max-w-md border border-white/10 bg-[#111314] p-7"><p className="text-sm text-white/55">Sign in with the authorized FOAMX team account to manage order status.</p><input type="email" placeholder="Admin email" value={adminEmail} onChange={e => setAdminEmail(e.target.value)} className="field mt-5"/><Button onClick={async () => { if (!supabase) { toast.error('Add Supabase credentials first.'); return; } const { error } = await supabase.auth.signInWithOtp({ email: adminEmail, options: { emailRedirectTo: window.location.origin } }); if (error) toast.error(error.message); else toast.success('Check your email for the secure sign-in link.'); }} className="mt-4 w-full rounded-none bg-[#d4a94d] py-5 text-xs font-black uppercase tracking-[.15em] text-black">Send secure sign-in link</Button></div> : <div className="mt-10 overflow-hidden border border-white/10"><div className="grid grid-cols-[1.4fr_1fr_1fr_1fr] gap-4 border-b border-white/10 bg-[#111314] p-4 text-[10px] uppercase tracking-[.18em] text-white/40"><span>Order</span><span>Customer</span><span>Total</span><span>Status</span></div>{adminOrders.length ? adminOrders.map(order => <div key={order.id} className="grid grid-cols-[1.4fr_1fr_1fr_1fr] gap-4 border-b border-white/10 p-4 text-sm"><span className="font-bold">{order.order_number}</span><span className="text-white/60">{order.customer_name}<br/><small>{order.phone}</small></span><span className="text-[#d4a94d]">{money(order.total)}</span><select value={order.status} onChange={e => updateStatus(order.id, e.target.value)} className="bg-transparent text-xs uppercase"><option className="bg-[#111314]" value="pending">Pending</option><option className="bg-[#111314]" value="confirmed">Confirmed</option><option className="bg-[#111314]" value="processing">Processing</option><option className="bg-[#111314]" value="shipped">Shipped</option><option className="bg-[#111314]" value="delivered">Delivered</option><option className="bg-[#111314]" value="cancelled">Cancelled</option></select></div>) : <div className="p-10 text-center text-sm text-white/40">No connected orders yet. Configure Supabase to activate the order console.</div>}</div>}</div></div>}
  </div>;
}
